Messenger: __CONIO_H Class Reference
__CONIO_H Class Reference
#include <conio.h>
Public Member Functions
__CONIO_H ()
~__CONIO_H ()
void clreol ()
void insline ()
void delline ()
void gotoxy (int x, int y)
void clrscr ()
void textbackground (int color)
void textcolor (short color)
int ungetch (int ch)
int getch_echo (bool echo=true)
int getch ()
int getche ()
int wherexy (int &x, int &y)
int wherex ()
int wherey ()
int kbhit ()
int putch (const char c)
int cputs (const char *str)
char * getpass (const char *prompt)
int gettext (int l, int t, int r, int b, void *destination)
Private Attributes
int bgc
Detailed Description
Definition at line 144 of file conio.h.
Constructor & Destructor Documentation
__CONIO_H()
__CONIO_H::__CONIO_H () inline
Definition at line 148 of file conio.h.
               {
      bgc=40;
      }
~__CONIO_H()
__CONIO_H::~__CONIO_H () inline
Definition at line 152 of file conio.h.
                {
      printf("\033[m");
      }
Member Function Documentation
clreol()
void __CONIO_H::clreol () inline
Definition at line 156 of file conio.h.
                 {
      printf("\033[K");
      }
clrscr()
void __CONIO_H::clrscr () inline
Definition at line 172 of file conio.h.
                 {
      printf( "\033[%dm\033[2J\033[1;1f",bgc);
      }
cputs()
int __CONIO_H::cputs (const char * str) inline
Definition at line 298 of file conio.h.
{
      printf(str);
      return 0;
      }
delline()
void __CONIO_H::delline () inline
Definition at line 164 of file conio.h.
                  {
      printf( "\033[1M");
      }
getch()
int __CONIO_H::getch () inline
Definition at line 238 of file conio.h.
               {
      getch_echo(false);
      }
Referenced by wherexy().
getch_echo()
int __CONIO_H::getch_echo (bool echo = true) inline
Definition at line 222 of file conio.h.
{
      struct termios oldt, newt;
      int ch;
      tcgetattr( STDIN_FILENO, &oldt );
      newt = oldt;
      newt.c_lflag &= ~ICANON;
      if(echo)
    newt.c_lflag &=  ECHO;
      else
    newt.c_lflag &= ~ECHO;
      tcsetattr( STDIN_FILENO, TCSANOW, &newt );
      ch = getchar();
      tcsetattr( STDIN_FILENO, TCSANOW, &oldt );
      return ch;
      }
Referenced by getch(), and getche().
getche()
int __CONIO_H::getche () inline
Definition at line 242 of file conio.h.
                {
      getch_echo(true);
      }
getpass()
char * __CONIO_H::getpass (const char * prompt) inline
Definition at line 303 of file conio.h.
{
      //implementada en unistd.h
      }
gettext()
int __CONIO_H::gettext (int l, int t, int r, int b, void * destination) inline
Definition at line 307 of file conio.h.
{
      }
gotoxy()
void __CONIO_H::gotoxy (int x, int y) inline
Definition at line 168 of file conio.h.
{
      printf("\033[%d;%df",y,x);
      }
insline()
void __CONIO_H::insline () inline
Definition at line 160 of file conio.h.
                  {
      printf( "\x1b[1L");
      }
kbhit()
int __CONIO_H::kbhit () inline
Definition at line 273 of file conio.h.
               {
      struct termios oldt, newt;
      int ch;
      int oldf;
      tcgetattr(STDIN_FILENO, &oldt);
      newt = oldt;
      newt.c_lflag &= ~(ICANON | ECHO);
      tcsetattr(STDIN_FILENO, TCSANOW, &newt);
      oldf = fcntl(STDIN_FILENO, F_GETFL, 0);
      fcntl(STDIN_FILENO, F_SETFL, oldf | O_NONBLOCK);
      ch = getchar();
      tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
      fcntl(STDIN_FILENO, F_SETFL, oldf);
      if(ch != EOF){
    ungetc(ch, stdin);
    return 1;
    }
      return 0;
      }
putch()
int __CONIO_H::putch (const char c) inline
Definition at line 293 of file conio.h.
{
      printf("%c",c);
      return (int)c;
      }
textbackground()
void __CONIO_H::textbackground (int color) inline
Definition at line 176 of file conio.h.
{
      switch(color%16){
      case BLACK:          bgc=40;break;
      case BLUE:           bgc=44;break;
      case GREEN:          bgc=42;break;
      case CYAN:           bgc=46;break;
      case RED:            bgc=41;break;
      case MAGENTA:        bgc=45;break;
      case BROWN:          bgc=43;break;
      case LIGHTGRAY:      bgc=47;break;
      case DARKGRAY:       bgc=40;break;
      case LIGHTBLUE:      bgc=44;break;
      case LIGHTGREEN:     bgc=42;break;
      case LIGHTCYAN:      bgc=46;break;
      case LIGHTRED:       bgc=41;break;
      case LIGHTMAGENTA:   bgc=45;break;
      case YELLOW:         bgc=43;break;
      case WHITE:          bgc=47;break;
    }
      }
textcolor()
void __CONIO_H::textcolor (short color) inline
Definition at line 197 of file conio.h.
{
      switch(color%16){
      case BLACK:          printf("\033[0;%d;%dm",30,bgc);break;
      case BLUE:           printf("\033[0;%d;%dm",34,bgc);break;
      case GREEN:          printf("\033[0;%d;%dm",32,bgc);break;
      case CYAN:           printf("\033[0;%d;%dm",36,bgc);break;
      case RED:            printf("\033[0;%d;%dm",31,bgc);break;
      case MAGENTA:        printf("\033[0;%d;%dm",35,bgc);break;
      case BROWN:          printf("\033[0;%d;%dm",33,bgc);break;
      case LIGHTGRAY:      printf("\033[0;%d;%dm",37,bgc);break;
      case DARKGRAY:       printf("\033[1;%d;%dm",30,bgc);break;
      case LIGHTBLUE:      printf("\033[1;%d;%dm",34,bgc);break;
      case LIGHTGREEN:     printf("\033[1;%d;%dm",32,bgc);break;
      case LIGHTCYAN:      printf("\033[1;%d;%dm",36,bgc);break;
      case LIGHTRED:       printf("\033[1;%d;%dm",31,bgc);break;
      case LIGHTMAGENTA:   printf("\033[1;%d;%dm",35,bgc);break;
      case YELLOW:         printf("\033[1;%d;%dm",33,bgc);break;
      case WHITE:          printf("\033[1;%d;%dm",37,bgc);break;
    }
      }
ungetch()
int __CONIO_H::ungetch (int ch) inline
Definition at line 218 of file conio.h.
                       {
      return ungetc(ch, stdin);
      }
wherex()
int __CONIO_H::wherex () inline
Definition at line 261 of file conio.h.
                {
      int x=0,y=0;
      wherexy(x,y);
      return x;
      }
wherexy()
int __CONIO_H::wherexy (int & x, int & y) inline
Definition at line 246 of file conio.h.
{
      printf("\033[6n");
      if(getch() != '\x1B') return 0;
      if(getch() != '\x5B') return 0;
      int in;
      int ly = 0;
      while((in = getch()) != ';')
      ly = ly * 10 + in - '0';
      int lx = 0;
      while((in = getch()) != 'R')
      lx = lx * 10 + in - '0';
      x = lx;
      y = ly;
      }
Referenced by wherex(), and wherey().
wherey()
int __CONIO_H::wherey () inline
Definition at line 267 of file conio.h.
                {
      int x=0,y=0;
      wherexy(x,y);
      return y;
      }
Member Data Documentation
bgc
int __CONIO_H::bgc private
Definition at line 146 of file conio.h.
Referenced by __CONIO_H(), clrscr(), textbackground(), and textcolor().
The documentation for this class was generated from the following file:
conio.h/conio.h