Messenger: History Class Reference
History Class Reference
Class History - contains the history of messages.
#include <History.h>
Public Member Functions
void add_message (const Message &message)
history_t get_history_from (const std::string &name)
history_t get_history_to (const std::string &name)
history_t get_undelivered_to (const std::string &name)
void set_delivered (std::size_t id)
Private Attributes
history_t _history
Detailed Description
Class History - contains the history of messages.
Definition at line 15 of file History.h.
Member Function Documentation
add_message()
void History::add_message (const Message & message)
Definition at line 3 of file History.cpp.
{
    _history.push_back(message);
}
Referenced by UserBase::deliver().
get_history_from()
history_t History::get_history_from (const std::string & name)
Definition at line 7 of file History.cpp.
{
    history_t result;
    for (auto& message : _history) {
        if (message.get_from() == name) {
            result.push_back(message);
        }
    }
    return result;
}
get_history_to()
history_t History::get_history_to (const std::string & name)
Definition at line 17 of file History.cpp.
{
    history_t result;
    for (auto& message : _history) {
        if (message.get_to() == name) {
            result.push_back(message);
        }
    }
    return result;
}
get_undelivered_to()
history_t History::get_undelivered_to (const std::string & name)
Definition at line 27 of file History.cpp.
{
    history_t result;
    for (auto& message : _history) {
        if (message.get_to() == name && !message.is_delivered()) {
            result.push_back(message);
        }
    }
    return result;
}
Referenced by UserBase::user_try_in().
set_delivered()
void History::set_delivered (std::size_t id)
Definition at line 37 of file History.cpp.
{
    for (auto& message : _history) {
        if (message.get_id() == id) {
            message.set_delivered();
            break;
        }
    }
}
Referenced by UserBase::set_delivered().
Member Data Documentation
_history
history_t History::_history private
Definition at line 24 of file History.h.
Referenced by add_message(), get_history_from(), get_history_to(), get_undelivered_to(), and set_delivered().
The documentation for this class was generated from the following files:
History.h
History.cpp