Messenger: Session Class Reference
Session Class Reference
Class Session - establishes a network connection.
#include <Session.h>
Public Member Functions
Session (tcp::socket socket, std::shared_ptr< UserBase > base)
void start ()
void write (const Message &message) override
Public Member Functions inherited from UserSession
virtual ~UserSession ()=default
virtual void write (const Message &message)=0
Private Types
enum { _max_data_size = 1024 * 32 }
Private Member Functions
void do_read_header ()
void do_read_data (std::size_t data_size)
void do_write (const char *data, std::size_t length)
Static Private Member Functions
static string_pair split_login (const std::string &name, const std::string &d)
Private Attributes
tcp::socket _socket
char _data [_max_data_size]
std::shared_ptr< UserBase > _base
Additional Inherited Members
Protected Attributes inherited from UserSession
std::string _name
Detailed Description
Class Session - establishes a network connection.
Parameters
socket Network socket.
sender Shared pointer to UserBase.
Definition at line 19 of file Session.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
_max_data_size
Definition at line 35 of file Session.h.
{ _max_data_size = 1024 * 32 };
Constructor & Destructor Documentation
Session()
Session::Session (tcp::socket socket, std::shared_ptr< UserBase > base) inline
Definition at line 21 of file Session.h.
            : _socket(std::move(socket)), _base(std::move(base)) {}
Member Function Documentation
do_read_data()
void Session::do_read_data (std::size_t data_size) private
Definition at line 28 of file Session.cpp.
{
    auto self(shared_from_this());
    boost::asio::async_read(_socket, boost::asio::buffer(_data, data_size),
        [this, self](boost::system::error_code ec, std::size_t length) {
            if (!ec) {
                Message message{std::string(_data, length)};
                if (message.get_type() == Type::REG) {
                    auto [name, password] = split_login(message.get_from(), "@");
                    if (_base->is_user(name)) {
                        write(Message(0, message.get_type(), name, message.get_to(),
                                      "Error. This name is already used."));
                    } else {
                        _base->user_out(_name);
                        _name = name;
                        _base->user_reg(_name, password, shared_from_this());
                        write(Message(0, message.get_type(), name, message.get_to(), "OK"));
                    }
                } else if (message.get_type() == Type::LOGIN) {
                    auto [name, password] = split_login(message.get_from(), "@");
                    if (!_base->is_user(name)) {
                        write(Message(0, message.get_type(), name, message.get_to(),
                                      "Error. User with this name is not registered."));
                    } else {
                        if (_base->user_try_in(name, password, shared_from_this())) {
                            _base->user_out(_name);
                            _name = name;
                        } else {
                            write(Message(0, message.get_type(), name, message.get_to(),
                                          "Error. Password is incorrect."));
                        }
                    }
                } else if (message.get_type() == Type::DIAL) {
                    if (!_base->is_user(message.get_to())) {
                        write(Message(0, Type::DIAL, message.get_from(), message.get_to(),
                                      "Error. User with this name is not registered."));
                    } else {
                        write(Message(0, Type::DIAL, message.get_from(), message.get_to(), "OK"));
                    }
                }
                if (message.get_type() == Type::MSG || message.get_type() == Type::FILE
                    || message.get_type() == Type::USER_TYPING) {
                    _base->deliver(message);
                }
                if (message.get_type() == Type::DELIVERED) {
                    _base->set_delivered(message.get_id());
                }
                do_read_header();
            } else {
                std::cout << "User out: " << _name << std::endl;
                _base->user_out(_name);
            }
        });
}
Referenced by do_read_header().
do_read_header()
void Session::do_read_header () private
Definition at line 12 of file Session.cpp.
{
    auto self(shared_from_this());
    boost::asio::async_read(_socket, boost::asio::buffer(_data, Message::header_size),
        [this, self](boost::system::error_code ec, std::size_t) {
            if (!ec) {
                std::size_t data_size = std::stoi(_data);
                if (data_size <= _max_data_size) {
                    do_read_data(data_size);
                }
            } else {
                std::cout << "User out: " << _name << std::endl;
                _base->user_out(_name);
            }
        });
}
Referenced by do_read_data(), and start().
do_write()
void Session::do_write (const char * data, std::size_t length) private
Definition at line 85 of file Session.cpp.
{
    auto self(shared_from_this());
    boost::asio::async_write(_socket, boost::asio::buffer(data, length),
        [this, self](boost::system::error_code ec, std::size_t /*length*/) {
            if (!ec) {
            } else {
                std::cout << "User out: " << _name << std::endl;
                _base->user_out(_name);
            }
        });
}
Referenced by write().
split_login()
string_pair Session::split_login (const std::string & name, const std::string & d) static private
Definition at line 98 of file Session.cpp.
{
    auto pos = name.find(d);
    return {name.substr(0, pos), name.substr(pos + 1)};
}
Referenced by do_read_data().
start()
void Session::start ()
Definition at line 3 of file Session.cpp.
                    {
    do_read_header();
}
write()
void Session::write (const Message & message) override virtual
Implements UserSession.
Definition at line 7 of file Session.cpp.
{
    std::string msg{message.serialize()};
    do_write(msg.c_str(), msg.length());
}
Referenced by do_read_data().
Member Data Documentation
_base
std::shared_ptr<UserBase> Session::_base private
Definition at line 38 of file Session.h.
Referenced by do_read_data(), do_read_header(), and do_write().
_data
char Session::_data[_max_data_size] private
Definition at line 36 of file Session.h.
Referenced by do_read_data(), and do_read_header().
_socket
tcp::socket Session::_socket private
Definition at line 34 of file Session.h.
Referenced by do_read_data(), do_read_header(), and do_write().
The documentation for this class was generated from the following files:
Session.h
Session.cpp