Messenger: MsgClient Class Reference
MsgClient Class Reference
Class MsgClient - asynchronous messenger client.
#include <MsgClient.h>
Public Member Functions
MsgClient (boost::asio::io_context &io_context, const tcp::resolver::results_type &endpoints)
void close ()
void parse_command (const std::string &command)
void user_typing ()
void print (const std::string &message, std::ostream &out=std::cout)
std::mutex & get_console_mutex ()
std::string get_peer_name ()
Private Types
enum { _max_data_size = 1024 * 32 }
Private Member Functions
void write (const Message &message)
void connect (const tcp::resolver::results_type &endpoints)
void do_read_header ()
void do_read_data (std::size_t data_size)
void do_write (const char *data, std::size_t length)
bool send_file (const std::string &filename)
std::string receive_file (const std::string &string)
Private Attributes
std::string _name
std::string _peer_name
Status _status
boost::asio::io_context & _context
tcp::socket _socket
tcp::resolver::results_type _endpoints
char _data [_max_data_size]
file_storage_t _file_storage
std::mutex _console_mutex
Static Private Attributes
static const std::size_t _max_file_size { 1000000 }
static const std::size_t _buffer_size { 32000 }
Detailed Description
Class MsgClient - asynchronous messenger client.
Parameters
context Provides the core I/O functionality.
endpoints Addresses of endpoints to connect .
Definition at line 31 of file MsgClient.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
_max_data_size
Definition at line 59 of file MsgClient.h.
{ _max_data_size = 1024 * 32 };
Constructor & Destructor Documentation
MsgClient()
MsgClient::MsgClient (boost::asio::io_context & io_context, const tcp::resolver::results_type & endpoints)
Definition at line 3 of file MsgClient.cpp.
        : _context(io_context), _socket(io_context), _endpoints(endpoints) {
    connect(endpoints);
}
Member Function Documentation
close()
void MsgClient::close ()
Definition at line 15 of file MsgClient.cpp.
                      {
    boost::asio::post(_context, [this]() { _socket.close(); });
}
Referenced by main().
connect()
void MsgClient::connect (const tcp::resolver::results_type & endpoints) private
Definition at line 19 of file MsgClient.cpp.
{
    boost::asio::async_connect(_socket, endpoints, [this](boost::system::error_code ec, const tcp::endpoint&) {
        if (!ec) {
            _status = Status::CONNECTED;
            print("Connection successful!");
            do_read_header();
        } else {
            print("Error: server offline!", std::cerr);
            _socket.close();
            _status = Status::DISCONNECTED;
        }
    });
}
Referenced by MsgClient().
do_read_data()
void MsgClient::do_read_data (std::size_t data_size) private
Definition at line 49 of file MsgClient.cpp.
{
    boost::asio::async_read(_socket, boost::asio::buffer(_data, data_size),
                            [this](boost::system::error_code ec, std::size_t length) {
            if (!ec) {
                Message message{std::string(_data, length)};
                if (message.get_type() == Type::REG) {
                    if (message.get_body() == "OK") {
                        print("Register successful.");
                        _name = message.get_from();
                        _status = Status::LOGIN;
                    } else {
                        print(message.get_body(), std::cerr);
                    }
                } else if (message.get_type() == Type::LOGIN) {
                    if (message.get_body() == "OK") {
                        print("Login successful.");
                        _name = message.get_from();
                        _status = Status::LOGIN;
                    } else {
                        print(message.get_body(), std::cerr);
                    }
                } else if (message.get_type() == Type::DIAL) {
                    if (message.get_body() == "OK") {
                        print("Dialog started.");
                        _peer_name = message.get_to();
                        _status = Status::DIALOG;
                    } else {
                        print(message.get_body(), std::cerr);
                    }
                } else if (_status == Status::DIALOG || _status == Status::LOGIN) {
                    if (message.get_type() == Type::MSG) {
                        write(Message(message.get_id(), Type::DELIVERED, _name));
                        print(message.get_time_str() + " " + message.get_from() + ": " + message.get_body());
                    } else if (message.get_type() == Type::USER_TYPING) {
                        print(message.get_from() + ": " + message.get_body());
                    } else if (message.get_type() == Type::FILE) {
                        write(Message(message.get_id(), Type::DELIVERED, _name));
                        std::string filename{receive_file(message.get_body())};
                        if (!filename.empty()) {
                            print(message.get_time_str() + " " + message.get_from() + ": "
                                + "Sent file \"" + filename + "\"");
                        }
                    }
                }
                do_read_header();
            }
            else {
                print("Error: connection lost!", std::cerr);
                _socket.close();
                _status = Status::DISCONNECTED;
            }
    });
}
Referenced by do_read_header().
do_read_header()
void MsgClient::do_read_header () private
Definition at line 33 of file MsgClient.cpp.
{
    boost::asio::async_read(_socket, boost::asio::buffer(_data, Message::header_size),
        [this](boost::system::error_code ec, std::size_t) {
            if (!ec) {
                std::size_t data_size = std::stoi(_data);
                if (data_size <= _max_data_size) {
                    do_read_data(data_size);
                }
            } else {
                print("Error: connection lost!", std::cerr);
                _socket.close();
                _status = Status::DISCONNECTED;
            }
        });
}
Referenced by connect(), and do_read_data().
do_write()
void MsgClient::do_write (const char * data, std::size_t length) private
Definition at line 103 of file MsgClient.cpp.
{
    boost::asio::async_write(_socket, boost::asio::buffer(data, length),
        [this](boost::system::error_code ec, std::size_t/* length*/) {
        if (!ec) {
        } else {
            print("Error: connection lost!", std::cerr);
            _socket.close();
            _status = Status::DISCONNECTED;
        }
    });
}
Referenced by write().
get_console_mutex()
std::mutex & MsgClient::get_console_mutex ()
Definition at line 239 of file MsgClient.cpp.
{
    return _console_mutex;
}
Referenced by main().
get_peer_name()
std::string MsgClient::get_peer_name ()
Definition at line 248 of file MsgClient.cpp.
{
    return _peer_name;
}
Referenced by main().
parse_command()
void MsgClient::parse_command (const std::string & command)
Definition at line 116 of file MsgClient.cpp.
{
    std::stringstream ss(command);
    std::string part, password;
    ss >> part;
    if (part == "reg") {
        ss >> part >> password;
        if (!password.empty()) {
            write(Message(0, Type::REG, part + "@" + password));
        } else {
            print("Warning. Password cannot be empty!", std::cerr);
        }
    } else if (part == "login") {
        ss >> part >> password;
        if (!password.empty()) {
            write(Message(0, Type::LOGIN, part + "@" + password));
        } else {
            print("Warning. Password cannot be empty!", std::cerr);
        }
    } else if (part == "dial") {
        if (_status == Status::LOGIN || _status == Status::DIALOG) {
            ss >> part;
            write(Message(0, Type::DIAL, _name, part));
        } else {
            print("Warning. You must register and login first!", std::cerr);
        }
    } else if (_status == Status::DIALOG) {
        if (part == "file") {
            ss >> part;
            if (!send_file(part)) {
                print("Warning. File does not exist or its size exceeds "
                      + std::to_string(_max_file_size / 1000000.f) + " mb!", std::cerr);
            }
        } else {
            if (part == "msg") {
                std::stringstream buf;
                buf << ss.rdbuf();
                part = buf.str().substr(1);
            } else {
                part = ss.str();
            }
            if (!part.empty()) {
                write(Message(0, Type::MSG, _name, _peer_name, part));
            }
        }
    } else {
        print("Warning. You must register, login and choose a recipient first!");
    }
}
Referenced by main().
print()
void MsgClient::print (const std::string & message, std::ostream & out = std::cout)
Definition at line 243 of file MsgClient.cpp.
{
    std::lock_guard lock(_console_mutex);
    out << message << std::endl;
}
Referenced by connect(), do_read_data(), do_read_header(), do_write(), and parse_command().
receive_file()
std::string MsgClient::receive_file (const std::string & string) private
Definition at line 210 of file MsgClient.cpp.
{
    std::stringstream ss{string};
    std::string filename;
    std::size_t file_id, i_block, blocks_count;
    ss >> file_id >> filename >> i_block >> blocks_count;
    std::stringstream buf;
    buf << ss.rdbuf();
    if (auto it = _file_storage.find(file_id); it != _file_storage.end()) {
        it->second.emplace(i_block, buf.str().substr(1));
    } else {
        _file_storage[file_id].emplace(i_block, buf.str().substr(1));
    }
    if (_file_storage[file_id].size() == blocks_count) {
        fs::create_directory(fs::path{"./" + _name + "/"});
        std::ofstream file(fs::path{"./" + _name + "/" + filename}, std::ios::binary);
        if (file.is_open()) {
            for (const auto& [id, block] : _file_storage[file_id]) {
                file.write(block.data(), block.length());
            }
            file.close();
            _file_storage.erase(file_id);
            return filename;
        }
    }
    return {};
}
Referenced by do_read_data().
send_file()
bool MsgClient::send_file (const std::string & filename) private
Definition at line 171 of file MsgClient.cpp.
{
    fs::path path{"./" + _name + "/" + filename};
    if (!fs::exists(path)) {
        path = "./" + filename;
        if (!fs::exists(path)) {
            return false;
        }
    }
    std::size_t filesize{fs::file_size(path)};
    if (filesize > _max_file_size) {
        return false;
    }
    std::ifstream file(path, std::ios::binary);
    if (file.is_open()) {
        std::string buffer(_buffer_size, '\0');
        std::size_t i_block = 0;
        std::string file_id;
        std::size_t blocks_count = std::ceil(static_cast<long double>(filesize) / _buffer_size);
        while (file) {
            file.read(buffer.data(), _buffer_size);
            if (i_block == 0) {
                file_id = std::to_string(std::hash<std::string>{}(std::string{buffer}));
            }
            if (file.gcount() != 0) {
                std::string block{file_id};
                block.append(" " + filename + " " + std::to_string(i_block) + " " + std::to_string(blocks_count) + " ");
                block.append(buffer, 0, file.gcount());
                write(Message(0, Type::FILE, _name, _peer_name, block));
            }
            ++i_block;
        }
        file.close();
        return true;
    }
    return false;
}
Referenced by parse_command().
user_typing()
void MsgClient::user_typing ()
Definition at line 165 of file MsgClient.cpp.
{
    if (_status == Status::DIALOG) {
        write(Message(0, Type::USER_TYPING, _name, _peer_name, "Typing a message..."));
    }
}
Referenced by main().
write()
void MsgClient::write (const Message & message) private
Definition at line 8 of file MsgClient.cpp.
{
    boost::asio::post(_context, [this, message]() {
        std::string msg{message.serialize()};
        do_write(msg.c_str(), msg.length());
    });
}
Referenced by do_read_data(), parse_command(), send_file(), and user_typing().
Member Data Documentation
_buffer_size
const std::size_t MsgClient::_buffer_size { 32000 } static private
Definition at line 63 of file MsgClient.h.
Referenced by send_file().
_console_mutex
std::mutex MsgClient::_console_mutex private
Definition at line 66 of file MsgClient.h.
Referenced by get_console_mutex(), and print().
_context
boost::asio::io_context& MsgClient::_context private
Definition at line 56 of file MsgClient.h.
Referenced by close(), and write().
_data
char MsgClient::_data[_max_data_size] private
Definition at line 60 of file MsgClient.h.
Referenced by do_read_data(), and do_read_header().
_endpoints
tcp::resolver::results_type MsgClient::_endpoints private
Definition at line 58 of file MsgClient.h.
_file_storage
file_storage_t MsgClient::_file_storage private
Definition at line 64 of file MsgClient.h.
Referenced by receive_file().
_max_file_size
const std::size_t MsgClient::_max_file_size { 1000000 } static private
Definition at line 62 of file MsgClient.h.
Referenced by parse_command(), and send_file().
_name
std::string MsgClient::_name private
Definition at line 52 of file MsgClient.h.
Referenced by do_read_data(), parse_command(), receive_file(), send_file(), and user_typing().
_peer_name
std::string MsgClient::_peer_name private
Definition at line 53 of file MsgClient.h.
Referenced by do_read_data(), get_peer_name(), parse_command(), send_file(), and user_typing().
_socket
tcp::socket MsgClient::_socket private
Definition at line 57 of file MsgClient.h.
Referenced by close(), connect(), do_read_data(), do_read_header(), and do_write().
_status
Status MsgClient::_status private
Definition at line 54 of file MsgClient.h.
Referenced by connect(), do_read_data(), do_read_header(), do_write(), parse_command(), and user_typing().
The documentation for this class was generated from the following files:
MsgClient.h
MsgClient.cpp